# Generated by Django 3.1.7 on 2021-03-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210305_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='2021/03/10', verbose_name='تصویر پروفایل'),
        ),
    ]
