# Generated by Django 3.1.7 on 2021-03-05 19:55

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pageBuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appBarColor', colorfield.fields.ColorField(default='#5F788A', max_length=18)),
                ('appBarTextColor', colorfield.fields.ColorField(default='#FFFFFB', max_length=18)),
                ('appBarTextColorOnHover', colorfield.fields.ColorField(default='#FFFFFB', max_length=18)),
                ('siteLogo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AppBarMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نام نمایشی')),
                ('pageUrl', models.CharField(blank=True, max_length=200, verbose_name='آدرس صفحه')),
                ('pageBuilder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pageBuilder.pagesmodel')),
            ],
        ),
    ]
