# Generated by Django 3.1.7 on 2021-03-06 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesitesettings',
            name='sidebarContent',
            field=ckeditor.fields.RichTextField(default='ساید بار را از تنظیمات ویرایش کنید'),
        ),
    ]
