# Generated by Django 3.1.7 on 2021-03-10 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0002_basesitesettings_sidebarcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesitesettings',
            name='copyrightText',
            field=ckeditor.fields.RichTextField(default='کپی رایت را از تنظیمات ویرایش کنید .'),
        ),
        migrations.AlterField(
            model_name='basesitesettings',
            name='siteLogo',
            field=models.ImageField(upload_to='2021/03/10'),
        ),
    ]
