# Generated by Django 3.1.7 on 2021-03-10 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0003_auto_20210310_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesitesettings',
            name='aboutSite',
            field=ckeditor.fields.RichTextField(default='متن درباره را از تنظیمات ویرایش کنید .'),
        ),
    ]
