# Generated by Django 3.1.7 on 2021-03-05 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_previewtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='2021/03/05'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewText',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
