# Generated by Django 3.1.7 on 2021-03-06 09:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210305_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='2021/03/06', verbose_name='تصویر پیشنمایش'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previewText',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='متن پیش نمایش'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
