# Generated by Django 3.1.7 on 2021-03-09 17:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210306_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('order', models.PositiveIntegerField()),
                ('targetUrl', models.URLField()),
                ('label', ckeditor.fields.RichTextField()),
                ('caption', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='2021/03/09', verbose_name='تصویر پیشنمایش'),
        ),
    ]
