# Generated by Django 3.1.7 on 2021-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210309_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidercontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
