# Generated by Django 3.1.7 on 2021-03-10 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210309_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='2021/03/10', verbose_name='تصویر پیشنمایش'),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='caption',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='image',
            field=models.ImageField(upload_to='2021/03/10'),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='label',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='targetUrl',
            field=models.CharField(max_length=200),
        ),
    ]
