# Generated by Django 3.1.7 on 2021-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210310_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previewImage',
            field=models.ImageField(upload_to='2021/03/11', verbose_name='تصویر پیشنمایش'),
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='image',
            field=models.ImageField(upload_to='2021/03/11'),
        ),
    ]
