# Generated by Django 3.1.7 on 2021-03-11 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('messages', ckeditor.fields.RichTextField()),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
