# Generated by Django 3.1.7 on 2021-03-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessages',
            name='icons',
            field=models.CharField(choices=[('Success', 'success'), ('Error', 'error'), ('Warning', 'warning'), ('Info', 'info'), ('Question', 'question')], default='Info', max_length=100),
        ),
    ]
