# Generated by Django 3.1.7 on 2021-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0002_popupmessages_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupmessages',
            name='icons',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('question', 'Question')], default='info', max_length=100),
        ),
    ]
