# Generated by Django 3.1.7 on 2021-03-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0003_auto_20210311_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupmessages',
            old_name='icons',
            new_name='icon',
        ),
    ]
