# Generated by Django 3.1.7 on 2021-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0004_auto_20210311_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupmessages',
            name='icon',
            field=models.CharField(choices=[('success', 'موفق'), ('error', 'ارور'), ('warning', 'هشدار'), ('info', 'اطلاعات'), ('question', 'سوال'), ('none', 'بدون آیکون')], default='info', max_length=100),
        ),
    ]
