# Generated by Django 3.1.7 on 2021-03-02 15:14

from django.db import migrations, models
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pageTitle', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('html', django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
    ]
