# Generated by Django 3.1.7 on 2021-03-05 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('pageTitle', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('html', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
