# Generated by Django 3.1.7 on 2021-03-02 15:26

from django.db import migrations, models
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pageBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='html',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='pageTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
