# Generated by Django 3.1.7 on 2021-03-02 15:38

from django.db import migrations
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pageBuilder', '0002_auto_20210302_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='html',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(),
        ),
    ]
