# Generated by Django 3.1.7 on 2021-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageBuilder', '0003_auto_20210302_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesmodel',
            name='html',
        ),
    ]
