# Generated by Django 3.1.7 on 2021-03-10 15:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
